/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "imtheapp"

include(":Multiplatform")
include(":Multiplatform:DTO")
include(":Multiplatform:Serialization")
include(":Multiplatform:Architecture")
include(":Multiplatform:Storage")

include(":Mobile")
include(":Mobile:Libraries:Common:SharedNetwork")
include(":Mobile:Libraries:Common:BeerGallery")
include(":Mobile:Libraries:Common:AsyncCachedImage")