load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "iOSUtilities",
    srcs = glob(["API/**/*.swift"]),
    module_name = "iOSUtilities",
    visibility = ["//visibility:public"],
)