include:
  - path: common/staticlib_settings.yml
    relativePaths: false

settingGroups:
  API:
    base:
      PRODUCT_ID_SUFFIX: .$(TARGET_NAME:lower:c99extidentifier).api
    groups:
      - Staticlib
