name: TestApp
include:
  - path: ../../../../Infrastructure/xcodegen-templates/app_extension_template.yml
    relativePaths: false
  - path: ../../../../Infrastructure/xcodegen-templates/application_template.yml
    relativePaths: false
  - path: ../../../../Infrastructure/xcodegen-templates/impl_template.yml
    relativePaths: false
  - path: ../../../../Infrastructure/xcodegen-templates/bundle_template.yml
    relativePaths: false
  - path: ../../../../Infrastructure/xcodegen-templates/test_kit_template.yml
    relativePaths: false
  - path: ../../../../Infrastructure/xcodegen-templates/tests_template.yml
    relativePaths: false
  - path: ../../../../Infrastructure/xcodegen-templates/app_tests_template.yml
    relativePaths: false
  - path: ../../../../Infrastructure/xcodegen-templates/common.yml
    relativePaths: false

settings:
  base:
    JAVA_HOME: /Users/alex/.sdkman/candidates/java/current
    FRAMEWORK_SEARCH_PATHS: $(SRCROOT)/../../../../Multiplatform/Architecture/.gradle_build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME) $(SRCROOT)/../../../BeerGallery/.gradle_build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)
    OTHER_LDFLAGS: $(inherited) -framework BeerGallery -framework Architecture

  configs:
    Debug:
      APP_BASE_PRODUCT_IDENTIFIER: $(SALUTE_C2C_BUNDLE_ID_DEVELOP)
      APP_BASE_PROFILE_IDENTIFIER: $(SALUTE_C2C_BASE_PROFILE_IDENTIFIER_DEVELOP)
    Release:
      APP_BASE_PRODUCT_IDENTIFIER: $(SALUTE_C2C_BUNDLE_ID_RELEASE)
      APP_BASE_PROFILE_IDENTIFIER: $(SALUTE_C2C_BASE_PROFILE_IDENTIFIER_RELEASE)
  groups:
    - Shared

settingGroups:
  DevelopmentTeam:
    base:
      DEVELOPMENT_TEAM: $(FORTENOVO_DEVELOPMENT_TEAM)
    groups:
      - DevelopmentTeams

  SaluteC2C:
    base:
      PRODUCT_BUNDLE_IDENTIFIER: $(APP_BASE_PRODUCT_IDENTIFIER)$(APP_PRODUCT_SUFFIX)
targets:
  TestApp:
    templates:
      - Application
    # settings:
    #   base:
    #     IPHONEOS_DEPLOYMENT_TARGET: 13.0
    #     PRODUCT_BUNDLE_IDENTIFIER: $(APP_BASE_PRODUCT_IDENTIFIER)
    #     PROVISIONING_PROFILE_SPECIFIER: $(APP_BASE_PROFILE_IDENTIFIER)
      # configs:
      #   Debug:
      #     ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-dev
      #     CODE_SIGN_ENTITLEMENTS: $(PROJECT_DIR)/Entitlements/Salute-Develop.entitlements
      #   Profile:
      #     ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-dev
      #     CODE_SIGN_ENTITLEMENTS: $(PROJECT_DIR)/Entitlements/Salute-Develop.entitlements
      #   AdHoc InHouse Release:
      #     ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-beta
      #     CODE_SIGN_ENTITLEMENTS: $(PROJECT_DIR)/Entitlements/Salute-Beta.entitlements
      #   AdHoc InHouse Beta:
      #     ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-beta
      #     CODE_SIGN_ENTITLEMENTS: $(PROJECT_DIR)/Entitlements/Salute-Release.entitlements
      #   Sberstore:
      #     ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-beta
      #     CODE_SIGN_ENTITLEMENTS: $(PROJECT_DIR)/Entitlements/Salute-Release.entitlements
      #   Release:
      #     ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      #     CODE_SIGN_ENTITLEMENTS: $(PROJECT_DIR)/Entitlements/Salute-Release.entitlements
      # groups:
      #   - DevelopmentTeam

    info:
      properties:
        AON_EXTENSION_IDENTIFIER: $(SALUTE_AON_EXTENSION_IDENTIFIER)
        APP_ICON_ASSET_NAME: $(ASSETCATALOG_COMPILER_APPICON_NAME)

        CFBundleName: CFBundleName_LOCALIZED
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: ""
            CFBundleURLSchemes:
              - companionapp

        ITSAppUsesNonExemptEncryption: false


        UIViewControllerBasedStatusBarAppearance: true

    preBuildScripts:
      - script: |
          cd "${SRCROOT}/../../../../"
          ./gradlew :Mobile:BeerGallery:embedAndSignAppleFrameworkForXcode
          ./gradlew :Multiplatform:Architecture:embedAndSignAppleFrameworkForXcode
        name: "Embed KMM Library"

