---
# Шаблон Xcodegen для расширений приложения, таких как Share Extension и др.
# Шаблон принимает Source файлы из выбранной директории с названием таргета.
# Пример:
# Target: AONExtension. Исходные файлы будут браться из Sourecs/AONExtension
# без исключений.
include:
  - path: build-settings/application_extension_settings.yml
    relativePaths: false

targetTemplates:
  AppExtension:
    type: app-extension
    platform: iOS

    settings:
      groups:
        - ApplicationExtension

    scheme: {}

    info:
      path: Sources/${target_name}/Info.plist
      properties:
        CFBundleDisplayName: ${target_name}
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)

    sources:
      - path: Sources/${target_name}/Info.plist
        optional: true

      - path: Sources/${target_name}
        includes:
          - "**/*.swift"
          - "**/*.[mhc]"

    buildImplicitDependencies: false
