---
# Шаблон Xcodegen для пакета с ресурсами.
# Шаблон принимает все файлы из директории с названием таргета
# Пример:
# Target: SDBundle. Пакет будет включать себя содержимое директории Sources/SDBundle
include:
  - path: build-settings/resources_settings.yml
    relativePaths: false

targetTemplates:
  Bundle:
    type: bundle
    platform: iOS

    settings:
      groups:
        - Resources

    info:
      path: Sources/${target_name}/Info.plist
      properties:
        CFBundlePackageType: BNDL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleSupportedPlatforms:
          - iPhoneOS

    sources:
      - path: Sources/${target_name}/Info.plist
        optional: true

      - path: Sources/${target_name}

    buildImplicitDependencies: false
