---
# Шаблон Xcodegen для таргета Unit Tests.
# Шаблон принимает:
# - Source файлы из выбранной директории с названием таргета в подпапке _Tests_.
# Пример:
# Target: SDFramework. Исходные файлы будут браться из
# Sources/SDFramework/Foo/_Tests/FooTests.swift.
# Также для таргета автоматически проставляется зависимость на основной таргет.
# Пример: FooFrameworkTests -> FooFramework.
include:
  - path: build-settings/unit_tests_settings.yml
    relativePaths: false

targetTemplates:
  Tests:
    type: bundle.unit-test
    platform: iOS

    settings:
      groups:
        - UnitTests

    sources:
      - path: Sources/${testingTarget}
        includes:
          - "**/_Tests_"

    dependencies:
      - target: ${testingTarget}
        embed: false
        link: true

    buildImplicitDependencies: false
