/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */

// buildscript {
//     repositories {
//         gradlePluginPortal()
//         google()
//         mavenCentral()
//     }
//     dependencies {
//         classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10")
//         classpath("com.android.tools.build:gradle:7.0.4")
//     }
// }

// allprojects {
//     repositories {
//         google()
//         mavenCentral()
//     }
// }