include:
  - path: cflags_settings.yml
    relativePaths: false

  - path: clang_settings.yml
    relativePaths: false

  - path: core_data_settings.yml
    relativePaths: false

  - path: gcc_settings.yml
    relativePaths: false

  - path: version_settings.yml
    relativePaths: false

  - path: development_teams_settings.yml
    relativePaths: false

settingGroups:
  Shared:
    base:
      ALWAYS_SEARCH_USER_PATHS: false
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: $(SBOL_DEVELOPMENT_TEAM) # TODO: Убрать?

      ENABLE_BITCODE: true
      ENABLE_STRICT_OBJC_MSGSEND: true
      IPHONEOS_DEPLOYMENT_TARGET: 14.0

      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks
      FRAMEWORK_SEARCH_PATHS: ${inherited} 

      SDKROOT: iphoneos
      SUPPORTS_MACCATALYST: false

      SWIFT_EMIT_LOC_STRINGS: true
      SWIFT_VERSION: 5.7

      TARGETED_DEVICE_FAMILY: 1
      VERSIONING_SYSTEM: apple-generic
      VALIDATE_PRODUCT: true

      PRODUCT_BUNDLE_IDENTIFIER: ru.sberbank.sberdevices.$(PROJECT_NAME:lower:c99extidentifier)$(PRODUCT_ID_SUFFIX)
      PRODUCT_NAME: $(TARGET_NAME:c99extidentifier)

    configs:
      Debug:
        ASSETCATALOG_COMPILER_OPTIMIZATION: time
        COPY_PHASE_STRIP: false
        DEBUG_INFORMATION_FORMAT: dwarf
        ENABLE_NS_ASSERTIONS: true
        ENABLE_TESTABILITY: true
        ONLY_ACTIVE_ARCH: true
        OTHER_SWIFT_FLAGS: >
          -Xfrontend -warn-long-function-bodies=150 
          -Xfrontend -warn-long-expression-type-checking=150
        STRIP_INSTALLED_PRODUCT: false
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(BUILD_TYPE) DEBUG
        SWIFT_COMPILATION_MODE: incremental
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        VALIDATE_PRODUCT: false

      Release:
        ASSETCATALOG_COMPILER_OPTIMIZATION: space
        COPY_PHASE_STRIP: true
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ENABLE_NS_ASSERTIONS: false
        ENABLE_TESTABILITY: false
        ONLY_ACTIVE_ARCH: false
        STRIP_INSTALLED_PRODUCT: true
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(BUILD_TYPE) RELEASE
        SWIFT_COMPILATION_MODE: wholemodule
        SWIFT_OPTIMIZATION_LEVEL: -O

    groups:
      - CFlags
      - Clang
      - GCC
      - Version
